CREATE DATABASE INVENTORY;
USE INVENTORY;
CREATE TABLE SOLDITEMS (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(80) NOT NULL, LOCATION VARCHAR(30) NOT NULL, IMAGE VARCHAR(2803) NOT NULL, LINK VARCHAR(2803) NOT NULL, DATESOLD DATETIME);
CREATE TABLE ITEMS (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(80) NOT NULL, LOCATION VARCHAR(30) NOT NULL, IMAGE VARCHAR(2803) NOT NULL, LINK VARCHAR(2803) NOT NULL, DATEADDED DATETIME);


